### PR TITLE
Update sv_SE.lang

### PR DESCRIPTION
**Pull request by Lunar-Dawn**

### CODE REVIEW

**Comment by Lunar-Dawn** [comment]
Don't merge, ponify fucked it up

**Comment by Vswe** [comment]
stallion?

**Comment by Lunar-Dawn** [comment]
Ponify fucked it upp stallions = men, stallion = man

**Comment by Lunar-Dawn** [comment]
https://chrome.google.com/webstore/detail/ponify/kaelfbndbnpddlehfmbhjnphpjljegae?hl=en

**Pull request closed without merging**
