### PR TITLE
Dutch Translations with the latest added lines

### PR DESCRIPTION
**Pull request by ghost**
Updated

### CODE REVIEW

**Comment by Redeye123** [comment]
Uhm please do Mijnkar the correct translation xD

**Comment by ghost** [comment]
Mijnkar is the translation of MineCart. Steves Carts is talking about Carts and not MineCarts. That's the reason why I did it like this. If you insist on it i will change it

**Comment by Redeye123** [comment]
Hmm now you say it never mind ill sit back in a corner xD

**Comment by spiderbiggen** [comment]
info.SC2:moduleConflictHowever=Gaat een probleem opleven met
info.SC2:moduleConflictAlso=Gaat ook een probleem opleven met

in these two translations i think "opleven" should be "opleveren"

info.SC2:moduleGroupToolShooter=[%1:Gereedschap|Gereedschappen] or [%1:Shieter|Shieters]
here shieter|shieters should be schieter|schieters

**Comment by ghost** [comment]
Thanks for the check, going to change those lines. After typing so many lines a little type error like that can happen :). Thanks agian and this will be updated with the next pull request in a few hours while i've added  the new translations as well

**Pull request merged**
