### PR TITLE
Create de_DE.lang

### PR DESCRIPTION
**Pull request by Galaxy2Alex**
"Early Alpha", untested due to lack of b2
I don't know if the german "Umlaute" (ä, ö, ü) are working.

### CODE REVIEW

**Comment by Galaxy2Alex** [comment]
...whoops, I forgot the second half. I'm on it.

**Comment by Lunar-Dawn** [comment]
Swedish ä & ö are working at least...

**Comment by Galaxy2Alex** [comment]
did you test it ingame already? Because as far as I remember, it didn't work properly for Forestry and Buildcraft.

**Comment by Lunar-Dawn** [comment]
Worked in his screenshot...
But that is SWEDISH ä & ö not "a + ¨" & "o + ¨"
Have no idea 'bout ü

**Comment by Galaxy2Alex** [comment]
If ä and ö are working, ü should work as well.
I'm not sure about the fourth special letter, ß (eszett)

**Comment by Lunar-Dawn** [comment]
Only one way to know, try.

**Pull request merged**
